<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-21FFCBE" failures="1" tests="5" name="TestRunner.Run" time="173.119" errors="0" timestamp="2024-06-12T21:58:35 IST" skipped="0">
  <testcase classname="TestRunner.Run" name="runScenario" time="29.844"/>
  <testcase classname="TestRunner.Run" name="runScenario" time="24.750"/>
  <testcase classname="TestRunner.Run" name="runScenario" time="26.036"/>
  <testcase classname="TestRunner.Run" name="runScenario" time="22.347"/>
  <testcase classname="TestRunner.Run" name="runScenario" time="70.142">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at StepDefinition.StepDef.user_can_view_confirmation_message(StepDef.java:269)
at âœ½.User can view confirmation message "The new customer has been added successfully."(file:///C:/Users/PradeepB/eclipse-workspace/CucumberFramework/./Features/Customers.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- TestRunner.Run -->
